name: CompatHelper
on:
  schedule:
    - cron: 33 0 * * *
jobs:
  CompatHelper:
    runs-on: ubuntu-latest
    steps:
      - name: Install "CompatHelper"
        shell: julia --color=yes {0}
        run: using Pkg; Pkg.add("CompatHelper")
      - name: Run CompatHelper
        shell: julia --color=yes {0}
        run: using CompatHelper; CompatHelper.main()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMPATHELPER_PRIV: ${{ secrets.DOCUMENTER_KEY }}
