name: Documentation

on:
  push:
    branches: "master"
    tags: ["*"]
  pull_request:
  release:

jobs:
  build:
    name: "Build and deploy"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1
      - name: Cache artifacts
        uses: julia-actions/cache@v2
      - uses: julia-actions/julia-docdeploy@releases/v1
        env:
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
